<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Be3.Health.Domain\Be3.Health.Domain.csproj" />
    <ProjectReference Include="..\Be3.Health.Infra\Be3.Health.Infra.csproj" />
  </ItemGroup>

</Project>
